name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Import aliveBar
        2. Call with these options...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Minimal code to reproduce the issue.
      render: typescript

  - type: input
    id: version
    attributes:
      label: Package Version
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      options:
        - Node.js
        - Bun
        - Deno
        - Other
    validations:
      required: true

  - type: input
    id: runtime-version
    attributes:
      label: Runtime Version
      placeholder: "Node 20.10.0 / Bun 1.1.0"
